[formatter.haskell]
command = "fourmolu"
options = [
  "--ghc-opt",
  "-XImportQualifiedPost",
  "--ghc-opt",
  "-XTypeApplications",
  "--record-brace-space",
  "true",
  "--single-constraint-parens",
  "never",
  "--mode",
  "inplace",
]
includes = ["*.hs"]

[formatter.cabal]
command = "cabal-fmt"
options = ["--inplace"]
includes = ["*.cabal"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.yaml]
command = "yamlfmt"
includes = ["*.yaml", "*.yml" ]
